### ISSUE TITLE
Add content - Analysis: Blast，throw error

### ISSUE THREAD

**Issue by horizon365** [erasche/docker-tripal#44]
![图片](https://user-images.githubusercontent.com/17285011/152904633-52ff5429-aeb3-4d02-9e7c-efa39cd82072.png)

In browser network debug tool, it shows [HTTP/1.1 500 Service unavailable (with message) 310ms] with below url.
http://127.0.0.1:3000/node/add/chado-analysis-blast?render=overlay
![图片](https://user-images.githubusercontent.com/17285011/152905139-13cae6d3-44d6-465a-af35-e9afeb9f0594.png)

**Comment by abretaud** [comment]
Hi!
Do you have more details in the docker logs?
How did you run your container?

**Comment by horizon365** [comment]
Hi, abretaud. thanks for you reply. The docker logs is show as follow:

`tripal_1  | x:80 116.6.99.217 - - [09/Feb/2022:02:05:37 +0000] "GET /node/add/chado-analysis-blast?render=overlay HTTP/1.1" 500 7380 "http://x:8210/node/add/chado-analysis-blast?render=overlay" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:95.0) Gecko/20100101 Firefox/95.0"`

and i use `docker-compose up ` to run my container.

**Comment by abretaud** [comment]
Can you paste here the content of your docker-compose.yml file?

**Comment by horizon365** [comment]
```
version: "2"
services:
  tripal:
    image: quay.io/galaxy-genome-annotation/tripal
    links:
      - db:postgres
    volumes:
      - /var/www/html/sites
      - /var/www/private
    environment:
      UPLOAD_LIMIT: 20M
      MEMORY_LIMIT: 128M
      VIRTUAL_HOST: 121.36.7.6
      # If you run the image on a different port, then BASE_URL must be set
      # correctly. If you run on :80 it should be OK to remove BASE_URL
      BASE_URL: "http://121.36.7.6:8210"
      BASE_URL_PROTO: "http://"
      DB_NAME: 'tripal'
      TRIPAL_DOWNLOAD_MODULES: "tripal_analysis_blast-7.x-2.x-dev"
      TRIPAL_GIT_CLONE_MODULES: "https://github.com/tripal/tripal_analysis_expression.git"
      TRIPAL_ENABLE_MODULES: "tripal_analysis_blast tripal_analysis_expression tripal_analysis_interpro"
    ports:
      - "8210:80"
  db:
    image: quay.io/galaxy-genome-annotation/chado
    environment:
      - POSTGRES_PASSWORD=postgres
        # The default chado image would try to install the schema on first run,
        # we just want the GMOD tools to be available.
      - INSTALL_CHADO_SCHEMA=0
      - INSTALL_YEAST_DATA=0
      - PGDATA=/var/lib/postgresql/data/
    volumes:
      - /var/lib/postgresql/data/
```
it is just as exactly the template in 'Readme.md',expect the ip and ports.
